### ISSUE TITLE
Wrong variable used in node_modules package

### ISSUE THREAD

**Issue by Ars6n9** [capacitor-community/capacitor-googlemaps-native#110]
**Describe the bug**

/Users/ars6n9/Projects/capp/node_modules/@capacitor-community/capacitor-googlemaps-native/android/src/main/java/com/hemangkumar/capacitorgooglemaps/CapacitorGoogleMaps.java:457: error: cannot find symbol
                    if (viewToRemove != null){
                        ^
  symbol: variable viewToRemove

**Expected behavior**
It should be viewToShow instead of viewToRemove at line 457

**Screenshots**
<img width="1364" alt="Capture d’écran 2021-09-27 à 14 10 53" src="https://user-images.githubusercontent.com/6042617/134905421-56031240-9f06-4bb2-b41d-3d3cd9f0fec2.png">

**Comment by hemangsk** [comment]
Nice catch @Ars6n9 ! Thanks for pointing this issue out. would you consider sending a PR for this?

**Comment by rastafan** [comment]
I believe this was fixed with #115

**Comment by hemangsk** [comment]
Yup, closing
