### ISSUE TITLE
Any Ionic Vue exemple ? 

### ISSUE THREAD

**Issue by GEnAdInE** [capacitor-community/capacitor-googlemaps-native#118]
Hello everyone , 
I'm looking for a working exemple of using this plugin with ionic and Vue JS. 
I've been trying to make it work but i can't. 
So if someone would be kind enough to share a Vue basic exemple that would be awsome.

Thank you very much.

**Comment by chiqors** [comment]
I really need this too.. Please enlighten me

**Comment by wait-matsu** [comment]
Hello.
I am not using Ionic, but I am using this library with Vue3 CompositionAPI and Capacitor.

Sample code to display a map
```
<template>
  <div id="map" ref="mapRef"></div>
</template>

<script lang="ts">
// vue
import { defineComponent, computed, ref, onMounted } from 'vue';

// capacitor
import { CapacitorGoogleMaps } from '@capacitor-community/capacitor-googlemaps-native';

export default defineComponent({
  setup() {
    const mapRef = ref();

    onMounted(() => {
      // Get the DOM to embed GoogleMap.
      const ref = mapRef.value as HTMLElement;
      const width = ref.clientWidth;
      const height = ref.clientHeight;
      const coords = ref.getBoundingClientRect();

      // create GoogleMap
      CapacitorGoogleMaps.create({
        width,
        height,
        x: coords.x,
        y: coords.y,
        latitude: curPos.value.lat,
        longitude: curPos.value.lng,
        zoom: 12,
      });

    return {
      mapRef,
    };
  },
});
</script>

<style scoped>
#map {
  width: 100vw;
  height: 100vh;
}
</style>
```

If you want to add markers, write the following in the process after CapacitorGoogleMaps.create.
```
CapacitorGoogleMaps.addListener('onMapReady', async () => {
  CapacitorGoogleMaps.addMarker({
    latitude: 35.689633,
    longitude: 139.692101,
    title: 'title',
    snippet: 'description',
  });
});
```

**Comment by GEnAdInE** [comment]
Thanks a lot , 
I managed to make it work (getting the not Implemented exception for web interface) in ionic by using :

 ` const ref = document.getElementById("map");` 

instead of  ` const ref = mapRef.value as HTMLElement;`

Unfortunately running on android isn't working for me but it looks like an issue with ionic more than an issue with the plugin itself.
