### ISSUE TITLE
Is there a feature for using direction API?

### ISSUE THREAD

**Issue by chiqors** [capacitor-community/capacitor-googlemaps-native#119]
I would like to know if there's one.

**Comment by fredroo** [comment]
+1

**Comment by fredroo** [comment]
How i can make directions on this plugin

**Comment by tafelnl** [comment]
This is outside the scope of this project. It should fairly simple and trivial to use the Direction API. See the official Google documentation on this: https://developers.google.com/maps/documentation/directions/overview

**Comment by ratnamyadav** [comment]
@tafelnl What about if we want to show directions between two points.
