### ISSUE TITLE
Where's API Reference? also does the development stopped?

### ISSUE THREAD

**Issue by chiqors** [capacitor-community/capacitor-googlemaps-native#125]
Hi, i am currently using this plugin. I want to know if i can have docs for all API functions/instances etc.. I need geometry spherical for computing distance in KM

**Comment by patrick-entinux** [comment]
Not sure if it helps but I usually use turfjs to calculate distance: https://www.npmjs.com/package/@turf/distance

**Comment by tafelnl** [comment]
Calculating distance is not in the scope of this plugin. As @patrick-entinux suggested, you should use another package for that.

About the documentation: As of v2 (still wip in the `next` branch, we have added extended documentation: https://capacitor-community.github.io/capacitor-googlemaps-native/
