### ISSUE TITLE
Task :app:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by apri23** [capacitor-community/capacitor-googlemaps-native#133]
hey, i found an error in my project, when i try to run android, can anyone help me?

[capacitor]         > Task :app:compileDebugJavaWithJavac FAILED
[capacitor]         C:\Users\nurul\ionic\newpickupp\android\app\src\main\java\com\pickupposindo\MainActivity.java:8: error: cannot find symbol
[capacitor]         public void onCreate(Bundle savedInstanceState) {
[capacitor]         ^
[capacitor]         symbol:   class Bundle
[capacitor]         location: class com.pickupposindo.MainActivity
[capacitor]         1 error
[capacitor]
[capacitor]         FAILURE: Build failed with an exception.
[capacitor]
[capacitor]         * What went wrong:
[capacitor]         Execution failed for task ':app:compileDebugJavaWithJavac'.
[capacitor]         > Compilation failed; see the compiler error output for details.

**Comment by dyegonery** [comment]
I have the same issue. Did you manage to find a solution for this?

**Comment by apri23** [comment]
just add

**Comment by apri23** [comment]
just add in MainActivity.java

package com.tesapp;
import android.os.Bundle; //add this
import com.hemangkumar.capacitorgooglemaps.CapacitorGoogleMaps;

import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        registerPlugin(CapacitorGoogleMaps.class);
    }
}
