### ISSUE TITLE
Allows to add overlap elements

### ISSUE THREAD

**Issue by NachoLarreta** [capacitor-community/capacitor-googlemaps-native#14]
Hi! thanks a lot for your work, I was spending a lot of time searching an alternative to capacitor with google maps native.
I was trying to add an overlap html element on the map and it's not working, with javascript works fine but with your plugin not, I'm not sure if in android and ios you can set an z-index or something like that to send to backgroud the map and front the html. 

Thanks!

**Comment by hemangsk** [comment]
Hey @NachoLarreta Glad you found the plugin useful. 

Regarding the overlapping HTML scenario, I suggest to try https://github.com/TeamHive/capacitor-webview-overlay/ to show your overlapping html element on the map by having a transparent webview in the same "div" in which you're showing the map.  

I'm not sure if it will work out but looks possible in theory and can be given a try.

**Comment by adnanhz** [comment]
Hey, is there any chance to have this resolved? How can I help?

**Comment by hemangsk** [comment]
Discussion continued at https://github.com/capacitor-community/capacitor-googlemaps-native/issues/84
