### ISSUE TITLE
Add docs using capacitor/docgen

### ISSUE THREAD

**Issue by hemangsk** [capacitor-community/capacitor-googlemaps-native#17]
https://www.npmjs.com/package/@capacitor/docgen

**Comment by tafelnl** [comment]
Added it to the next major: https://github.com/DutchConcepts/capacitor-googlemaps-native/blob/next/API_REFERENCE.md

**Comment by tafelnl** [comment]
Since we've made major progress with v2 and its documentation (https://capacitor-community.github.io/capacitor-googlemaps-native) (still WIP though) I will close this issue.
