### ISSUE TITLE
The map is always visible on everything else on the page

### ISSUE THREAD

**Issue by MelanieMarval** [capacitor-community/capacitor-googlemaps-native#18]
I have a question, is it possible to put the map under everything? Or put everything on the map? because i tried with css and everything comes out under the map no matter what i do.

It should be something like this.
[https://github.com/mapsplugin/cordova-plugin-googlemaps#how-does-this-plugin-work-android-ios](url)

**Comment by hemangsk** [comment]
Unfortunately, its not possible presently. Do the .hide() and .show() methods sound like a viable workaround?

**Comment by MelanieMarval** [comment]
hide and show do not work, the idea is that elements can be placed on the map not to hide it

**Comment by hemangsk** [comment]
Related to https://github.com/hemangsk/capacitor-googlemaps-native/issues/18

**Comment by hemangsk** [comment]
Related to https://github.com/hemangsk/capacitor-googlemaps-native/issues/14

**Comment by creativiii** [comment]
Any idea how and if this could be implemented?

**Comment by hyun-yang** [comment]
@hemangsk @creativiii 

I had a similar issue like this and I solved it using hide() and show() method as follows. 

It's a Ionic 5 + capacitor 3 project. 

Hope this helps.

`async showGeolocation() {
    CapacitorGoogleMaps.hide()
      .then(async (result) => {
        const alert = await this.alertController.create({
          header: 'Geolocation',
          message: this.tapLatLng.latitude + ' : ' + this.tapLatLng.longitude,
          buttons: [
            {
              text: 'OK',
              handler: () => {
                CapacitorGoogleMaps.show();
              }
            },
            {
              text: 'CANCEL',
              handler: () => {
                CapacitorGoogleMaps.show();
              }
            }
          ]
        });
        await alert.present();
      });
  }`

**Comment by hemangsk** [comment]
Discussion continued about possible solutions at pinned issue #84
