### ISSUE TITLE
Show blue dots icon on current location Google Maps

### ISSUE THREAD

**Issue by tototares** [capacitor-community/capacitor-googlemaps-native#19]
Is there any way to show your current locations on the map? When you use google maps, there is a blue dot which shows your location and direction. I thought "enableCurrentLocation()" is doing that, but it seems that this method just enable the location button.
![Screen Shot 2020-11-22 at 15 32 51](https://user-images.githubusercontent.com/1064024/99906638-815f5a00-2cd8-11eb-8d62-3bbae65109ac.png)

**Comment by hemangsk** [comment]
Hey, sorry for the late response here. Definitely a bug. enableCurrentLocation should ideally show this blue dot as well. Not sure what the exact problem is atm, but I'll try to look into it next week

**Comment by quaz579** [comment]
Any update on this?  I'd love to be able to use this plugin but I need to be able to display my location.

**Comment by hemangsk** [comment]
@quaz579  @tototares  Hey y'all! not much updates on this one from my side. Still trying to figure out the problem.

**Comment by hemangsk** [comment]
Haven't managed android to work here yet. iOS fixes are now merged.

**Comment by tafelnl** [comment]
After debugging for a long time. I found the issue on Android!

If you take a look at the [example app activity](https://github.com/googlemaps/android-samples/blob/master/ApiDemos/java/app/src/v3/java/com/example/mapdemo/RawMapViewDemoActivity.java)
it says:

> This shows how to create a simple activity with a raw MapView and add a marker to it. This requires forwarding all the important lifecycle methods onto MapView.

So - at least how I understand it - we will have to implement the following methods:
`onResume`, `onStart`, `onStop`, `onPause`, `onDestroy` and `onLowMemory`

These four: `onResume`, `onStop`, `onPause`, `onDestroy` can be simply accomplished be utilizing the helper methods provided by Capacitor. For `onResume` for example it is like this:

```java
    @Override
    protected void handleOnResume() {
        if (mapView != null) {
            mapView.onResume();
        }
        super.handleOnResume();
    }
```

`onStart` does not have such a helper method. But as far as I am aware we can simply run `onStart` directly after creating the view. So something like this:
```java
...
    @PluginMethod()
    public void create(PluginCall call) {
    ...
                mapView.onCreate(null);
                mapView.onStart(); // this line should be added
                mapView.getMapAsync(ctx);
    ...
    }
...
```

As for `onLowMemory` I do not really now what to do with that one. But I do not think that that one is really crucial anyway.

**Comment by hemangsk** [comment]
This is great @tafelnl thank you so much for nailing this issue down. I had lost hope here but its so good to see it solved finally! 

Yes, onLowMemory definitely looks low priority. good thing that rest of the important lifecycle method work. Do you want to send a patch?

**Comment by tafelnl** [comment]
Will try and send a PR tomorrow :)

**Comment by tafelnl** [comment]
I just sent in a PR
