### ISSUE TITLE
Cannot find name 'DOMRect'

### ISSUE THREAD

**Issue by abcoskn** [capacitor-community/capacitor-googlemaps-native#30]
Today, my project suddenly giving this error, icannot build the project with this line, how can i solve this problem?
```
[app-scripts] [12:16:00]  typescript: src/pages/stores-map/stores-map.ts, line: 63
[app-scripts]             Cannot find name 'DOMRect'.
[app-scripts]       L62:      });
[app-scripts]       L63:      const boundingRect = this.mapView.nativeElement.getBoundingClientRect() as DOMRect
```

**Comment by hemangsk** [comment]
@abcoskn, Are you sure this is related to this library? This doesn't seem related to package to me, but looks like a typescript setup issue.

**Comment by tafelnl** [comment]
Closing issue because it's gone stale.
