### ISSUE TITLE
Exists any beta version working with capacitor 3 beta ?

### ISSUE THREAD

**Issue by togro** [capacitor-community/capacitor-googlemaps-native#36]
Exists any version working with capacitor 3 beta ?

I'm trying with this version , but methods doesn't exists , and CapacitorGoogleMapsWeb (referenced by CapacitorGoogleMaps) not have any code ...

**Comment by gerciljunio** [comment]
@togro i was also in need! did you get any solution or are you waiting too?

**Comment by togro** [comment]
Switch to javascript version by the moment , when some version work we back to that plugin

**Comment by gerciljunio** [comment]
@togro cool, maybe i'll have to do the same! @hemangsk have any forecast for launching support for capacitor 3? thanks!

**Comment by hemangsk** [comment]
Working on it! eTA ~a week or so. apologies for the late response here.

**Comment by ChiKaLiO** [comment]
How much does google charge for js api ?

**Comment by hemangsk** [comment]
https://github.com/capacitor-community/capacitor-googlemaps-native/pull/45

**Comment by hemangsk** [comment]
Hey y'all, v3 support is closer. It'll be really great if you can give the v3 branch a try and provide any feedback.

The main change is that we are using new Permissions requests implementation from Capacitor v3. https://capacitorjs.com/docs/plugins/android#implementing-permission-requests, therefore, the plugin now just defines the permission which it needs in the annotation. Devs can use checkPermissions() and requestPermissions() methods to work with permissions required for this plugin. Let me know how it goes! cc @togro @gerciljunio @ChiKaLiO

**Comment by aacassandra** [comment]
hey @hemangsk, i installed this in v3 branch. how do i use this in capacitor v3. isn't the function const {CapacitorGoogleMaps} = Plugins; "Plugins" from the capacitor/core is outdated. how do i get the CapacitorGoogleMaps in capacitor 3. can i use as below?:

import {CapacitorGoogleMaps} from '' capacitor-googlemaps-native "

like other capacitor v3 plugins. new way almost using like this and not using " const {} = Plugins"

**Comment by hemangsk** [comment]
For ref https://github.com/capacitor-community/capacitor-googlemaps-native/pull/45#issuecomment-851930297

**Comment by hemangsk** [comment]
v3 Support is now merged. Closing this issue
