### ISSUE TITLE
Support for Launch URLs

### ISSUE THREAD

**Issue by hemangsk** [capacitor-community/capacitor-googlemaps-native#5]
https://developers.google.com/maps/documentation/ios-sdk/urlscheme

**Comment by hemangsk** [comment]
As per https://developers.google.com/maps/documentation/urls/get-started , We don't need a Google API key to use Maps URLs. This features allows users to specify map configuration and open Google maps application (installed on their phones, nothing to do with maps SDK) with that config .

**Comment by hemangsk** [comment]
I'll keep this open to evaluate user interest in this feature. Feel free to ping me here if you feel this will be a good addition!

**Comment by tafelnl** [comment]
I think this would be a little out of scope for this project. The Maps URL API is already very simple and elegant. IMHO, it just adds noise and maintenance headaches to this library. Instead I would just link to the Maps URL docs in the readme for example.

**Comment by tafelnl** [comment]
@selected-pixel-jameson let's discuss your comment on #85 here. Why would you like this to be implemented in the SDK? In my honest opinion it shouldn't be too difficult to just use the URL api google already provides. Buy maybe I am missing something. Could you please elaborate on that?

**Comment by tafelnl** [comment]
This feature will not implemented in the foreseeable future. I have added documentation about this in the (still WIP) docs: https://capacitor-community.github.io/capacitor-googlemaps-native/#/about/out-of-scope-features

I am going to close this issue for now.
