### ISSUE TITLE
Info Windows

### ISSUE THREAD

**Issue by selected-pixel-jameson** [capacitor-community/capacitor-googlemaps-native#52]
Has there been any progress on the Info Windows? This is a feature that multiple clients of mine need.

**Comment by hemangsk** [comment]
Will be easier to do this after https://github.com/capacitor-community/capacitor-googlemaps-native/issues/65

**Comment by hemangsk** [comment]
@selected-pixel-jameson , at the moment it is possible create a marker with title and snippet, and doing that will open an info window when the marker is tapped.
