### ISSUE TITLE
No podspec found for `CapacitorCommunityCapacitorGooglemapsNative` in  `../../node_modules/@capacitor-community/capacitor-googlemaps-native`

### ISSUE THREAD

**Issue by hyun-yang** [capacitor-community/capacitor-googlemaps-native#53]
**Describe the bug**
I created Ionic project which uses capacitor 3.0.

After installing this plugin then run **npx cap sync** it generate following error.

No podspec found for `CapacitorCommunityCapacitorGooglemapsNative` in  `../../node_modules/@capacitor-community/capacitor-googlemaps-native`

Here is Ionic info

Ionic:

   Ionic CLI                     : 6.16.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.8
   @angular-devkit/build-angular : 12.0.2
   @angular-devkit/schematics    : 12.0.2
   @angular/cli                  : 12.0.2
   @ionic/angular-toolkit        : 4.0.0

Utility:

   cordova-res : 0.15.3
   native-run  : 1.3.0

System:

   NodeJS : v14.17.0 (/usr/local/bin/node)
   npm    : 6.14.13
   OS     : macOS Big Sur

And  Ionic package.json dependencies info.
...
"dependencies": {
    "@angular/common": "~12.0.1",
    "@angular/core": "~12.0.1",
    "@angular/fire": "^6.1.5",
    "@angular/forms": "~12.0.1",
    "@angular/platform-browser": "~12.0.1",
    "@angular/platform-browser-dynamic": "~12.0.1",
    "@angular/router": "~12.0.1",
    "@capacitor-community/capacitor-googlemaps-native": "^1.0.0",
    "@capacitor/core": "3.0.0",
    "@capacitor/geolocation": "^1.0.0",
    "@capacitor/ios": "^3.0.0",
    "@capacitor/push-notifications": "^1.0.0",
    "@capacitor/splash-screen": "^1.0.0",
    "@capacitor/status-bar": "^1.0.0",
    "@ionic/angular": "^5.5.2",
    "@ionic/storage-angular": "^3.0.6",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "firebase": "^8.6.3",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  ...      

**To Reproduce**
1. Create Ionic 5 + Capacitor 3 project.
2. npm i --save @capacitor-community/capacitor-googlemaps-native
3. npx cap sync
4. then It generate following errors

✖ Updating iOS native dependencies with pod install - failed!
✖ update ios - failed!
[error] Analyzing dependencies
        [!] No podspec found for `CapacitorCommunityCapacitorGooglemapsNative` in
        `../../node_modules/@capacitor-community/capacitor-googlemaps-native`

**Comment by hemangsk** [comment]
Thanks for your report. This is fixed via https://github.com/capacitor-community/capacitor-googlemaps-native/pull/55 and released in 1.0.1

**Comment by hyun-yang** [comment]
The issue has been resolved.  

Thanks.
