### ISSUE TITLE
CocoaPods could not find compatible versions for pod "CapacitorCommunityCapacitorGooglemapsNative"

### ISSUE THREAD

**Issue by jongbonga** [capacitor-community/capacitor-googlemaps-native#61]
**Describe the bug**
✖ update ios: 
[error] Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "CapacitorCommunityCapacitorGooglemapsNative":
  In Podfile:
    CapacitorCommunityCapacitorGooglemapsNative (from `../../node_modules/@capacitor-community/capacitor-googlemaps-native`)

Specs satisfying the `CapacitorCommunityCapacitorGooglemapsNative (from `../../node_modules/@capacitor-community/capacitor-googlemaps-native`)` dependency were found, but they required a higher minimum deployment target.

what should the minimum deployment target be?

I'm getting the same issue as #53 even tho I'm on the latest version
**Additional context**
`"@capacitor-community/capacitor-googlemaps-native": "^1.0.2"`

**Comment by hemangsk** [comment]
> what should the minimum deployment target be?

12

**Comment by jongbonga** [comment]
Does the plugin require Capacitor 3?

**Comment by hemangsk** [comment]
Yes, it requires v3.

**Comment by jongbonga** [comment]
Thank you.
I was trying on v2 which as 11 as deployment target
