### ISSUE TITLE
Removing a marker

### ISSUE THREAD

**Issue by hyun-yang** [capacitor-community/capacitor-googlemaps-native#62]
**Is your feature request related to a problem? Please describe.**
As you can see the screenshot I attached, I can add a marker using 'didTabAt' event. 
However, I'd like to keep only one marker to indicate 'here is the destination'
In other words,  remove/clear existing marker feature is needed.

**Does this feature exist in the Google Maps SDK for android and iOS? Please link the documentation for this feature.**
Adding a marker/Removing a marker
https://developers.google.com/maps/documentation/ios-sdk/marker#maps_ios_markers_remove_marker-swift

**Describe the solution you'd like**
When didTapAt event fired,  I'd like to call removeMarker or clearMarker to remove existing marker or markers.

**Screenshot**
![didTapAt](https://user-images.githubusercontent.com/2142419/120793671-8734d280-c57a-11eb-8d6e-8c6a3765aa98.png)

**Comment by hemangsk** [comment]
Hi @hyun-yang , could you try .clear() for this. Ref https://github.com/capacitor-community/capacitor-googlemaps-native/blob/master/src/definitions.ts#L79

**Comment by hyun-yang** [comment]
@hemangsk oops,  how did I miss this method.  I was in a hurry when I tested it.
And It works perfectly fine, you can close this issue now.
Thanks.
