### ISSUE TITLE
I get code : "UNIMPLEMENTED" in IonicVue

### ISSUE THREAD

**Issue by usanzadunje** [capacitor-community/capacitor-googlemaps-native#73]
I get code : "UNIMPLEMENTED" when i try to use this plugin with IonicVue.

Specific error that i get is : "CapacitorGoogleMaps" plugin is not implemente on android

In template i have : <div id="map" ref="map"></div>

And in mounted hook i have : 
CapacitorGoogleMaps.create({
      width: 200,
      height: 200,
      x: 20,
      y: 20,
      latitude: -33.86,
      longitude: 151.20,
      zoom: 12,
    });

**Comment by usanzadunje** [comment]
I regenerated apk file and it worked. Closed

**Comment by selected-pixel-jameson** [comment]
I'm getting this same error on iOS using the `next` branch. Any suggestions?
