### ISSUE TITLE
Refactor: Split the Plugin class into smaller classes

### ISSUE THREAD

**Issue by hemangsk** [capacitor-community/capacitor-googlemaps-native#8]

**Comment by TartanLeGrand** [comment]
I'm thinking of using the same class naming as cordova-plugin-googlemaps.

- PluginCircle -> Everything related to the circle
- PluginGeocoder -> Everything related to the geocoder
- PluginLocationService -> Everything related to the location
- PluginMap -> Everything related to the map
- PluginMarker -> Everything related to the marker
- PluginPolygon -> Everything related to the polygon
- PluginPolyline -> Everything related to the polyline

**Comment by tafelnl** [comment]
As far as I know, splitting the methods annotated with `@PluginMethod` among multiple classes, is not (yet) supported by Capacitor. However other concepts and classes can be split up of course.

**Comment by tafelnl** [comment]
Since we've made major progress with this in v2 I will close this issue (although its still WIP but we need to clean up the issues).
