### ISSUE TITLE
IonFab button on map

### ISSUE THREAD

**Issue by thiras** [capacitor-community/capacitor-googlemaps-native#87]
**Describe the bug**
The floating Action Button stays behind the map view. I've tried to pass z-index both the map div and the button but didn't help.

**Screenshots**
<img src="https://user-images.githubusercontent.com/5150432/124524353-6d99db80-de03-11eb-8541-18a41e3463d1.jpg" width="200">
<img src="https://user-images.githubusercontent.com/5150432/124524355-72f72600-de03-11eb-8049-38d9436909c2.jpg" width="200">

**Comment by DwieDima** [comment]
This is a WIP feature request.
Progress can be found here #84

**Comment by thiras** [comment]
Thank you very much. I'm closing this issue in favor of #84
